// GENERATED by tool/gen_dart_seeds.py from data/. Do not edit.

/// The Chinese term pack.
///
/// Community-sourced and unvetted. Every entry takes a default category
/// and severity, because the source carries neither. Expect false
/// positives. Load it only when you handle Chinese text.
///
/// ```dart
/// import 'package:vulgarity/vulgarity.dart';
/// import 'package:vulgarity/lang/zh.dart';
///
/// final filter = (VulgarityFilterBuilder()
///       ..useDefaultSeed()
///       ..addSeed(seedZh))
///     .build();
/// ```
library;

/// 463 terms for Chinese.
const String seedZh = r'''
{
  "schema": 1,
  "profile": "fold-v1",
  "lang": "zh",
  "name": "Chinese",
  "vetted": false,
  "source": "https://github.com/master-wayne7/safe_text",
  "license": "MIT",
  "note": "Community-sourced list for Chinese. Nobody vetted these terms one by one, and the source carries no category or severity, so every entry takes category 'profanity' and severity 3. A term of 6 characters or fewer requires a word boundary. Expect false positives. Load this pack only when you handle text in this language.",
  "entries": [
    {
      "t": "aichai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "baakgwai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "banjau",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "bapo",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "batpo",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "bizui",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "boklui",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "caonima",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "caufahhai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "chaodiwangxauzu",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "chaohai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "checongmachinchin",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "chedan",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "cheelunseen",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "chiangjian",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "chibai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "chuckdeela",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "chuksangdoubutyu",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "daibohmui",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "dewneigorloong",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diao",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "dieuleilomo",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diewlei",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "dillaylomo",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "dingleigorfai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "dingleigorseefutlong",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "dingneigawfye",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "dioleoseiloumeihaui",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diukaoleigehzhui",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diulasing",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diulay",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "diulaylomo",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diulaylowmow",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diulayseefut",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diuleigohhai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diuleilaumau",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diuleilomo",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diuleiloumouhai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diuleilowdau",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diuleitsuenga",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diuneilomo",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diuneipookgai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diunelomo",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "diuniasing",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "doleilomochauhai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "faichaai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "feigeicheung",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "feihai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "fighcai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "gaajai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "ganniniang",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "gausigwai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "goniangyangde",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "gose",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "guitao",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "gunnimadedan",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "gwanleilunseeah",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "haiyeung",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "hamgafugwei",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "hamgatsanpukgai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "hamkachan",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "hamkaling",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "hamlung",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "hamsuplow",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "hoeseiahneagorbakchee",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "huisei",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "humgacharm",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "humlun",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "jekchau",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "jenggacan",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "jiba",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "jibai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "jibaikanina",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "juepa",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "jurjur",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "jutoumolou",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "kaizi",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "kakhamaloseye",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "kaoyao",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "kauwhai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "kneehowkialan",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "laanhooi",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "lanjiao",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "lantou",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "lanyeung",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "laufompei",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "lawbaaktau",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "layciewmea",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "leilowmow",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "lokchat",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "louhai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "lunyeung",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "malagebi",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "mawlawcha",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "moksarm",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "munghai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "munhuwlaygoma",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "naizi",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "nangyeung",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "naoshengchao",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "neifeiyaochow",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "neigohaiyanhoseah",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "ngohjauyimlei",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "ngonghai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "ngongkau",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "niamakachauhai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "nimabi",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "nimadenai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "nimamageirendiao",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "nishishenjiingbing",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "nowtsan",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "ongqinxiang",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "pc蛋蛋",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "pingyingchaonimadegiba",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "pokgai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "pootho",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "pukgai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "qunide",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "qusi",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "rinigexianrenbanban",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "saatjawlei",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "sawtsawtdeifatfatdei",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "saybahtpoh",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "seiahneadorpukgai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "seihamgachanseipukgai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "seihoi",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "seiyeemjai",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "seiyuntao",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "seksei",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "seksi",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "seksii",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "seungseiah",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "seyhai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "shabi",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "sharbie",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "sheeaahbee",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "shotao",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "siegouna",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "sielanthau",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "sitappa",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "sixi",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "souhai",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "tamade",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "teniangde",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "tianpo",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "tianwodan",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "tiulei",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "tounima",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "tsaodande",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "tsat",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "tsatgaulun",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "tsattao",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "tsattou",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "wocao",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "wokao",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "wori",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "xiabi",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "yeem",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "yudamful",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "yuksimah",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "yumtongla",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "ㄊㄋㄋㄉ",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "ㄙㄞ你公",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "ㄙㄞ你娘",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "ㄙㄞ你母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "ㄙㄞ你爸",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "ㄙㄞ你老師",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "ㄙㄞ你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "三個代婊",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "三個呆婊",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "三去車侖",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "三浦愛佳",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "三陪小姐",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "下老子一跳",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "不要屄脸",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "不要屄臉",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "不要脸的东西",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "不要臉的東西",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "丧心病狂",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "个老子的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "乳波臀浪",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "乳臭未乾",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "乳臭未干",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "交射臉上",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "人畜共患病",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "人體炸彈",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "从我面前消失",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他奶奶的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他奶娘的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他妈ㄉ王八蛋",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他妈巴子",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他妈的鸟",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他媽個逼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他媽巴子",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他媽的智障",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他媽的逼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "他媽的鳥",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "以莖至洞",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "低三下四",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你不是东西",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你不是人",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你不是東西",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你个傻比",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你个狗屁",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你丫挺的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你丫欠揍",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你二大爷的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你他妈的去死吧",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "你他妈的看什么",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "你他媽的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你他马的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你以为你在跟谁说话",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "你以为你是谁",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你会后悔的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你個狗屁",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你在講什麽屁話",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "你在講什麽鳥話",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "你在讲什么屁话",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "你在讲说什么鸟话",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "你奶奶的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你她馬的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你她马的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你妈的屄",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你娘卡好",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你娘雞掰",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你媽了妹",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你媽的屄",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你它妈的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你它马的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你怎么回事",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你是个混球",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你是什么东西",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你是什麽東西",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你有病啊",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你疯了吗",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你的脑子进水啊",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "你真是一个废物",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "你真烦人",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你真让我恶心",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你給我滾",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "你给我滚",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "來幹一炮",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "先奸後殺",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "公共汽車",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "公共汽车",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "关你屁事",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "关我屁事",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "关我鸟事",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "其言粪土也",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "出售假幣",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "出售帳號",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "出售手槍",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "出售槍支",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "出售此號",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "出售神符",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "利己主义",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "别再浪费我的时间了",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "别找借口",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "别跟我胡扯",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "别那样和我说话",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "半瓶子醋",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "去你奶奶的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "去你妈的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "去你媽的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "去吃大便",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "双峰微颤",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "叫你生孩子沒屁股眼",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "叫你生孩子没屁股眼",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "叫你生孩子长痔疮",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "吃飽飯沒事干",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "吃饱了撑的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "吸你的屌",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "吸你的蛋蛋",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "吸我的屌",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "咸家伶哇是大懶趴",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "噴精在臉上",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "塞你娘卡好",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "塞你老师",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "塞你老師",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "塞你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "墮胎醫生",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "夜勤病棟",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "大脑进水",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "大麻樹脂",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "太平公主",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹你媽b",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹你媽逼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹你祖宗",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹呼你勇",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹哩娘操機歪",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹女人猛射精",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹妳老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹尼娘勒",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹我要射了",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹的你好爽",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹的你挖挖叫",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "幹齁你爽",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "弟大勿勃",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "強效失意藥",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "性免費電影",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "恩塔特昆斯特",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "您杯卡好",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "您母卡好",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "成人圖片",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "成人小說",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "成人影視",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "成人文學",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "成人漫畫",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "成人網站",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "成人論壇",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "成人電影",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "我操你祖宗十八代",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "我的天啊",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "我真后悔这辈子遇到你",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "我都腻了",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "我靠or我尻",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "我鳥他的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "我鸟他的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "戳爆你的奶",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "戴綠帽子",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "戴绿帽子",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "打第三回合",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "投毒殺人",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "抽你丫的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "捅你的大雞巴",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "捏爆你的奶",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "捲毛捲雞掰",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "援助交際",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "操你全家",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "操你奶奶",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "操你媽的b",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "操你祖宗",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "操你老妈",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "操你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "操妳全家",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "操妳祖宗",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "放你妈的屁",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "放你妈的狗屁",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "放你妈的狗臭屁",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "放你媽的屁",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "放你媽的狗屁",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "放你媽的狗臭屁",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "日你老娘",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "日你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "智力障碍",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "智力障礙",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "有屁快放",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "有話快說",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "机机歪歪",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "杀人不眨眼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "東亞病夫",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "機機歪歪",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "欠幹大雞掰",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "欲火焚身",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "死不要脸",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "死不要臉",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "沒屁股眼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "没屁股眼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "没长眼啊",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "泰國人妖",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "淫水直流",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "淫水賤貨",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "淫語連連",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "混賬王八蛋",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "混账王八蛋",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "湿透的内裤",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "滚你妈屄",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "滚你妈的蛋",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "滾你媽屄",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "滾你媽的蛋",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "激情小電影",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "激情電影",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "濕透的內褲",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "火眼邪神",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "無恥之徒",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "無頭蒼蠅",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "狂操你全家",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "狗娘养的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "狗娘養的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "狗屁不通",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "狗操賣逼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "狗狼养的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "王八羔子",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "玫瑰花结",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "珍珠項鍊",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "珍珠项炼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "生兒子沒屁眼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "生孩子沒屁眼",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "畜牲狗養貓帶大",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "瞎鸡巴扯",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "神经衰弱",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "禽兽不如",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "粗制嗎啡",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "糙你祖宗",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "網石棒辣椒",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "美女視頻",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "老不死的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "老而不死",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "肏你妈的屄",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "肏你媽的屄",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "肏你祖宗十八代",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "自殺手冊",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "自殺指南",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "自製手槍",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "舔你的大懶巴",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "舔你的大雞巴",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "舔我雞巴",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "良心被狗吃了",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "色情小電影",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "色情服務",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "色情網站",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "色情電影",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "草你媽靠",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "草的你媽",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "西格海尔",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "見伍姑娘",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "见五姑娘",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "論他媽的",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "豬生狗養貓帶大",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "買賣槍支",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "賽你老北",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "賽你老師",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "賽你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "賽妳阿母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "赛你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "赛妳阿母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "車侖女干",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "逼你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "遊戲工作人員",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "遊戲工程師",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "遊戲發獎員",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "遊戲管理者",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "遠程偷拍",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "那是你的问题",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "關我鳥事",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "阴户口交",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "陰小撕大",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "陰戶口交",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "雙峰微顫",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "雞巴在癢",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "雞巴郎做雞巴代",
      "cat": "profanity",
      "sev": 3
    },
    {
      "t": "雞雞在癢",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "雞雞好癢",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "顏面騎乘",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "颜面骑乘",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "馬賣馬屁",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "駛你老師",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "駛你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "騎女人狂射精",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "马马虎虎",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "驶你老师",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "驶你老母",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "高麗棒子",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "麻醉乙醚",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "黃色圖片",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "黃色小說",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "黃色小電影",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "黃色影視",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "黃色文學",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "黃色漫畫",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "黃色網站",
      "cat": "profanity",
      "sev": 3,
      "w": true
    },
    {
      "t": "黃色電影",
      "cat": "profanity",
      "sev": 3,
      "w": true
    }
  ],
  "allow": []
}
''';
