#!/usr/bin/env python3
"""Compile the seed documents into Dart source.

The .NET build embeds data/*.json straight into the assembly. Dart has no such
step, and a Flutter web app cannot read a file, so the JSON becomes Dart source
instead.

  data/seed.json      -> dart/lib/src/seed_data.g.dart   (always compiled in)
  data/seed.<lang>.json -> dart/lib/lang/<lang>.dart     (import to use)

Each pack sits in its own library. An app that never imports one leaves it out
of the build, so an unused pack costs nothing.

Run:   python3 tool/gen_dart_seeds.py
Check: python3 tool/gen_dart_seeds.py --check
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
DART = os.path.join(ROOT, "dart")

LANGUAGES = ["ar", "de", "es", "fa", "fr", "hi", "it", "ko", "nl", "pl", "ru", "th", "vi", "zh"]

BANNER = "// GENERATED by tool/gen_dart_seeds.py from data/. Do not edit."


def raw_string(text):
    """Wrap JSON in a Dart raw triple-quoted string."""
    if "'''" in text:
        raise SystemExit("seed JSON holds a triple quote, so a raw string will not work")
    if text.endswith("'"):
        raise SystemExit("seed JSON ends with a quote, so a raw string will not work")
    return "r'''\n" + text + "''';"


def camel(code):
    return code[0].upper() + code[1:]


def build():
    files = {}

    english = open(os.path.join(DATA, "seed.json"), encoding="utf-8").read()
    files[os.path.join(DART, "lib", "src", "seed_data.g.dart")] = "\n".join([
        BANNER,
        "",
        "/// The bundled English term list, hand-curated.",
        "///",
        "/// It compiles into the library, so [VulgarityFilter.createDefault] needs",
        "/// no file access. That matters on Flutter web, which cannot read a file.",
        "library;",
        "",
        "const String kSeedEn = " + raw_string(english),
        "",
    ])

    names = []
    for code in LANGUAGES:
        path = os.path.join(DATA, "seed." + code + ".json")
        content = open(path, encoding="utf-8").read()
        doc = json.loads(content)
        name = "seed" + camel(code)
        names.append((code, name, doc["name"], len(doc["entries"])))

        files[os.path.join(DART, "lib", "lang", code + ".dart")] = "\n".join([
            BANNER,
            "",
            "/// The " + doc["name"] + " term pack.",
            "///",
            "/// Community-sourced and unvetted. Every entry takes a default category",
            "/// and severity, because the source carries neither. Expect false",
            "/// positives. Load it only when you handle " + doc["name"] + " text.",
            "///",
            "/// ```dart",
            "/// import 'package:vulgarity/vulgarity.dart';",
            "/// import 'package:vulgarity/lang/" + code + ".dart';",
            "///",
            "/// final filter = (VulgarityFilterBuilder()",
            "///       ..useDefaultSeed()",
            "///       ..addSeed(" + name + "))",
            "///     .build();",
            "/// ```",
            "library;",
            "",
            "/// " + str(len(doc["entries"])) + " terms for " + doc["name"] + ".",
            "const String " + name + " = " + raw_string(content),
            "",
        ])

    # The barrel. Importing it pulls in every pack, so the doc comment says so.
    lines = [
        BANNER,
        "",
        "/// Every optional language pack in one import.",
        "///",
        "/// This library references all " + str(len(LANGUAGES)) + " packs, so importing it",
        "/// puts them all in your build. To keep an app small, import only the",
        "/// packs you need from `package:vulgarity/lang/<code>.dart` instead.",
        "library;",
        "",
    ]
    lines.append("import 'src/seed_data.g.dart';")
    lines += ["import 'lang/" + code + ".dart';" for code in LANGUAGES]
    lines.append("")
    lines += ["export 'lang/" + code + ".dart';" for code in LANGUAGES]
    lines += [
        "",
        "/// Language codes this package carries, English included.",
        "const List<String> kAvailableLanguages = <String>[",
        "  'en',",
    ]
    lines += ["  '" + code + "'," for code in LANGUAGES]
    lines += [
        "];",
        "",
        "/// Every OPTIONAL pack, keyed by language code.",
        "///",
        "/// English is not in this map, because it is compiled into the library",
        "/// itself. Use [languageSeed], which resolves every code including 'en'.",
        "const Map<String, String> kLanguageSeeds = <String, String>{",
    ]
    lines += ["  '" + code + "': " + name + "," for code, name, _, _ in names]
    lines += [
        "};",
        "",
        "/// Returns the seed document for [code], English included.",
        "///",
        "/// Pass this straight to a builder or a preset:",
        "///",
        "/// ```dart",
        "/// final filter = VulgarityFilter.fromPreset(",
        "///   json,",
        "///   languageResolver: languageSeed,",
        "/// );",
        "/// ```",
        "///",
        "/// Throws [ArgumentError] when this package carries no pack for the code.",
        "String languageSeed(String code) {",
        "  if (code == 'en') {",
        "    return kSeedEn;",
        "  }",
        "  final String? seed = kLanguageSeeds[code];",
        "  if (seed == null) {",
        "    throw ArgumentError.value(",
        "      code,",
        "      'code',",
        "      'No pack for this language. Available: '",
        "          \"${kAvailableLanguages.join(', ')}\",",
        "    );",
        "  }",
        "  return seed;",
        "}",
        "",
    ]
    files[os.path.join(DART, "lib", "languages.dart")] = "\n".join(lines)

    return files, names


def main():
    check = "--check" in sys.argv
    files, names = build()

    stale = []
    for path, content in files.items():
        if check:
            current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if current != content:
                stale.append(os.path.relpath(path, ROOT))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)

    if check:
        if stale:
            print("STALE: " + ", ".join(stale))
            return 1
        print("Dart seeds are current")
        return 0

    total = sum(n[3] for n in names)
    print("English seed compiled into dart/lib/src/seed_data.g.dart")
    print("%d packs, %d terms, written to dart/lib/lang/" % (len(names), total))
    print("wrote %d files" % len(files))
    return 0


if __name__ == "__main__":
    sys.exit(main())
