// GENERATED by tool/gen_dart_seeds.py from data/. Do not edit.

/// Every optional language pack in one import.
///
/// This library references all 14 packs, so importing it
/// puts them all in your build. To keep an app small, import only the
/// packs you need from `package:vulgarity/lang/<code>.dart` instead.
library;

import 'src/seed_data.g.dart';
import 'lang/ar.dart';
import 'lang/de.dart';
import 'lang/es.dart';
import 'lang/fa.dart';
import 'lang/fr.dart';
import 'lang/hi.dart';
import 'lang/it.dart';
import 'lang/ko.dart';
import 'lang/nl.dart';
import 'lang/pl.dart';
import 'lang/ru.dart';
import 'lang/th.dart';
import 'lang/vi.dart';
import 'lang/zh.dart';

export 'lang/ar.dart';
export 'lang/de.dart';
export 'lang/es.dart';
export 'lang/fa.dart';
export 'lang/fr.dart';
export 'lang/hi.dart';
export 'lang/it.dart';
export 'lang/ko.dart';
export 'lang/nl.dart';
export 'lang/pl.dart';
export 'lang/ru.dart';
export 'lang/th.dart';
export 'lang/vi.dart';
export 'lang/zh.dart';

/// Language codes this package carries, English included.
const List<String> kAvailableLanguages = <String>[
  'en',
  'ar',
  'de',
  'es',
  'fa',
  'fr',
  'hi',
  'it',
  'ko',
  'nl',
  'pl',
  'ru',
  'th',
  'vi',
  'zh',
];

/// Every OPTIONAL pack, keyed by language code.
///
/// English is not in this map, because it is compiled into the library
/// itself. Use [languageSeed], which resolves every code including 'en'.
const Map<String, String> kLanguageSeeds = <String, String>{
  'ar': seedAr,
  'de': seedDe,
  'es': seedEs,
  'fa': seedFa,
  'fr': seedFr,
  'hi': seedHi,
  'it': seedIt,
  'ko': seedKo,
  'nl': seedNl,
  'pl': seedPl,
  'ru': seedRu,
  'th': seedTh,
  'vi': seedVi,
  'zh': seedZh,
};

/// Returns the seed document for [code], English included.
///
/// The code is matched without regard to case, so 'EN', 'En' and 'en'
/// all resolve. A language tag arrives upper-cased often enough --- from
/// a locale, a header, a database column --- that refusing one would be
/// a trap.
///
/// Pass this straight to a builder or a preset:
///
/// ```dart
/// final filter = VulgarityFilter.fromPreset(
///   json,
///   languageResolver: languageSeed,
/// );
/// ```
///
/// Throws [ArgumentError] when this package carries no pack for the code.
String languageSeed(String code) {
  final String key = code.toLowerCase();
  if (key == 'en') {
    return kSeedEn;
  }
  final String? seed = kLanguageSeeds[key];
  if (seed == null) {
    throw ArgumentError.value(
      code,
      'code',
      'No pack for this language. Available: '
          "${kAvailableLanguages.join(', ')}",
    );
  }
  return seed;
}
